# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: Start_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rleft_shoulder_pan_joint
    - rleft_shoulder_lift_joint
    - rleft_elbow_joint
    - rleft_wrist_1_joint
    - rleft_wrist_2_joint
    - rleft_wrist_3_joint
    - rright_shoulder_pan_joint
    - rright_shoulder_lift_joint
    - rright_elbow_joint
    - rright_wrist_1_joint
    - rright_wrist_2_joint
    - rright_wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rleft_shoulder_pan_joint
      - rleft_shoulder_lift_joint
      - rleft_elbow_joint
      - rleft_wrist_1_joint
      - rleft_wrist_2_joint
      - rleft_wrist_3_joint
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rright_shoulder_pan_joint
      - rright_shoulder_lift_joint
      - rright_elbow_joint
      - rright_wrist_1_joint
      - rright_wrist_2_joint
      - rright_wrist_3_joint